### ISSUE TITLE
React prop-types 사용여부 결정

### ISSUE THREAD

**Issue by ramram1048** [boostcamp-2020/IssueTracker-20#41]
![image](https://user-images.githubusercontent.com/48747221/97515028-77955000-19d3-11eb-8fcc-03d36f26056a.png)

eslint-plugin-react에서 prop-types를 이용할 것을 권장하고 있음.

## prop-types

React component의 상태를 담당하는 prop에 type을 지정해, prop에 잘못된 type이 들어오면 error가 나오도록 설정하는 것. 
TS처럼 type checking이 가능해져 디버깅이 편해진다. 
TS와 다른 점은, build가 아닌 runtime에 type checking이 발생하게 된다.

- eslint-plugin-react: <https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md>
- react 공식문서: <https://reactjs.org/docs/typechecking-with-proptypes.html>

## 사용할 경우

패키지 설치
```bash
npm i prop-types
```

각 React component에
```jsx
import PropTypes from 'prop-types';

class Greeting extends React.Component {
  render() {
    return (
      <h1>Hello, {this.props.name}</h1>
    );
  }
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

## 사용하지 않을 경우

frontend의 `.eslintrc.json`에 예외 처리
```json
{
  "rules": {
    "react/prop-types": "off"
  }
}
```

**Comment by hongzzi** [comment]
사용해보는 것도 좋을 것 같아요 👍
