### ISSUE TITLE
front에서 async, await사용시 ReferenceError

### ISSUE THREAD

**Issue by hongzzi** [boostcamp-2020/IssueTracker-20#92]
## 문제
![image](https://user-images.githubusercontent.com/41413618/98114634-e1888a80-1ee8-11eb-9d6b-fcbbc2ba72fd.png)
async await 문법을 사용하면 에러남.
이유는 babel 문제...........

이거때문에 promise로 바꾼 함수가 있었는데 결국 에러 해결 ㅠㅠ

bable 문제로 polyfil 설치해서 webpack, babel 설정파일 수정

**Comment by ramram1048** [comment]
#94 #118
